### ISSUE TITLE
Order "suggested wish list" items in the app by ID # 

### ISSUE THREAD

**Issue by chenkath** [chenkath/hummings#1]
I made some edits to "suggested wish list" copy.  Now the list is ordered by last update date.  I would like the list to be ordered by ID # when displayed in the app.

**Comment by ptrikutam** [comment]
This is complete here: https://github.com/ptrikutam/hummings/commit/1a18254ce27e448239d0255a504c7fae1030ba37

Can we please file issues in https://github.com/ptrikutam/hummings/issues, that way we can connect the code up to the issues directly (since they're the same project / repo).

**Comment by chenkath** [comment]
This issue was moved to ptrikutam/hummings#101
